#! /bin/sh


. ~/.scripts/source

bspc config border_width       $BORDER
bspc config window_gap         $GAP

bspc config left_padding 	    0
bspw config right_padding 	  0
bspc config bottom_padding 	  0
bspc config top_padding 		  $PANEL_HEIGHT

bspc config normal_border_color		$BORDER_COLOR
bspc config focused_border_color	$LIGHTGREEN

bspc config split_ratio         	0.52
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true
bspc config focus_follows_pointer	true

bspc monitor -d Home Web Work Media Game Misc

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
sysinfo &
