#! /bin/sh

. ~/.scripts/source

bspc config focused_border_color $YELLOW
bspc config normal_border_color $BBLACK

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc config auto_cancel  true

bspc monitor -d Home Web Files Media Torrent Sys Misc

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a yad floating=on

panel &
sysinfo &
now_playing &

