#! /bin/sh

. source

num_mon=$(bspc query -M | wc -l)
trans_r="%{B#242424}%{U#242424} %{B#212121}%{U#212121} %{B#1F1F1F}%{U#1F1F1F} %{B#1C1C1C}%{U#1C1C1C} %{B#1A1A1A}%{U#1A1A1A} %{B#171717}%{U#171717} %{B#141414}%{U#141414} "
trans_l="%{B#141414}%{U#141414} %{B#171717}%{U#171717} %{B#1A1A1A}%{U#1A1A1A} %{B#1C1C1C}%{U#1C1C1C} %{B#1F1F1F}%{U#1F1F1F} %{B#212121}%{U#212121} %{B#242424}%{U#242424} "

trans_r_alt="%{B#242424}%{U#404040} %{B#212121}%{U#383838} %{B#1F1F1F}%{U#303030} %{B#1C1C1C}%{U#292929} %{B#1A1A1A}%{U#212121} %{B#171717}%{U#1A1A1A} %{B#141414}%{U#141414} "
trans_l_alt="%{B#141414}%{U#141414} %{B#171717}%{U#1A1A1A} %{B#1A1A1A}%{U#212121} %{B#1C1C1C}%{U#292929} %{B#1F1F1F}%{U#303030} %{B#212121}%{U#383838} %{B#242424}%{U#404040} "

while read -r line ; do
	case $line in
		M*)
			music="${line#?}"
			;;
		u*)
			updates="${line#?}"
			;;
		S*)
			# clock output
			sysinfo="${line#?}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos${name}"
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos${name}"
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{B$BBLACK}%{U$YELLOW}%{+o} ${name} %{o-}%{B-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{B$BBLACK}%{U$YELLOW}%{+o} ${name} %{o-}%{B-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{B$CYAN}%{U$YELLOW}%{+o} ${name} %{o-}%{B-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{U$BLUE}%{B#333333}%{+o} ${name} %{o-}%{B-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{U$BBLACK}%{B#262626}%{+o} ${name} %{o-}%{B-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{U$BRED}%{B#262626}%{+o} ${name} %{o-}%{B-}"
						;;
					L*)
						# layout
						layout="${name}"
						;;
				esac
				shift
			done
			;;
	esac
	printf '%s\n' "%{l}${music}%{c}${trans_l_alt}${wm_infos}${trans_r_alt}%{r}${updates}${sysinfo}"
done
